### ISSUE TITLE
ignore padding

### ISSUE THREAD

**Issue by j4k0xb** [adrientoub/vscode-base64utils#11]
Doesn't work with the string `dGVzdA` (no ==) and shows no error message either
I suggest to try to convert it without the isBase64 check (or maybe only use it for showing a warning message)
Although it could allow invalid input, but it's the users choice to run the decode command

**Comment by adrientoub** [comment]
I have added this feature in 53d58fac5b17a23937e7e824b230ee2c7415477d, thanks for your comment.
I will close this once I publish a version with this feature.

**Comment by adrientoub** [comment]
Released 1.2.4 with this feature.
