### ISSUE TITLE
command 'extension.Base64D' not found

### ISSUE THREAD

**Issue by mcpiroman** [adrientoub/vscode-base64utils#6]
Whenever I invoke a command I get:

[Window Title]
Visual Studio Code

[Content]
Command 'Base64: change text from base64.' resulted in an error (command 'extension.Base64D' not found)

[OK]

Even after 'Restart Window'

**Comment by adrientoub** [comment]
Hello mcpiroman,
I have updated the extension to 1.2.1 to fix this issue, please report back if something is still not right.
Thanks a lot for the report I was not able to detect it during testing!
