### ISSUE TITLE
VS Code Extension v1.2.0 breaks base64/gunzip conversion

### ISSUE THREAD

**Issue by kent-id** [adrientoub/vscode-base64utils#7]
I'm not sure if this relates to this issue: https://github.com/adrientoub/vscode-base64utils/issues/6

Since v1.2.0, all the following seem to be broken (does nothing):
- change text from base64
- change test to base64
- gunzip-b64
- gzip-base64

Reverting to v1.1.0 fixes the issue. Let me know if there is any way I can grab some logs or something to help debug this.

**Reproducible on:**
- VS Code for Mac: Version: 1.62.3 (Universal)
- Same issue observed in my colleague's laptops using Windows/WSL with Ubuntu 20.04 (at least 2 people has this issue)

**Comment by adrientoub** [comment]
Hello kent-id,
It is indeed related to the other issue. I have published a new version 1.2.1 that should fix all existing issues with the classic VS Code extension. Adding support for web extensions unfortunately broke it and I hope it doesn't happen anymore.
Thanks for your report as it allowed me to discover the issue. Please report any other issue you find here.
