### ISSUE TITLE
Context menu entry texts

### ISSUE THREAD

**Issue by KolyaKorruptis** [adrientoub/vscode-base64utils#8]
I would like to suggest to change these context menu entry texts:
`Base64: change text from base64.`
to 
`Base64: Decode`

As well as:
`Base64: change text to base64.`
to 
`Base64: Encode`

**Comment by adrientoub** [comment]
Makes sense, do you want to make a PR?

**Comment by KolyaKorruptis** [comment]
#9

**Comment by adrientoub** [comment]
I have published the new version on the VS Code Marketplace
